### ISSUE TITLE
`frames.jsonl` not available

### ISSUE THREAD

**Issue by danieldeutsch** [ValentinaPy/RoleQGeneration#3]
There are a couple of places in the code where there is a hard-coded path to a file called `frames.jsonl`:
https://github.com/ValentinaPy/RoleQGeneration/blob/168eb664d146b7e4e50b56a1ac6ea7a25743e797/predict_questions.py#L68-L69
Is this a resource that you are able to add to the repository?

Thanks!

**Comment by ValentinaPy** [comment]
Oh, good catch, the file can be found in role_lexicon/frames.jsonl. I updated the path so it works from the root of the project.

**Comment by danieldeutsch** [comment]
Great, thanks! However, that file doesn't actually exist in the repository. Maybe frames.ontonotes.jsonl or frames.unified_propbank.jsonl?

**Comment by ValentinaPy** [comment]
Oops, right, it should be frames.ontonotes.jsonl. I fixed it now! Thanks for the patience.

**Comment by ValentinaPy** [comment]
Hi Daniel,

I was just made aware that the frames.ontonotes.jsonl file doesn't work with the script! Sorry! I pushed the frames.jsonl file now and I tested the script and now it should work as needed. Please use the updated script.
