### ISSUE TITLE
Unmatching format between frames.ontonotes.jsonl and PropBankRoleFinder

### ISSUE THREAD

**Issue by najoungkim** [ValentinaPy/RoleQGeneration#4]
Hi Valentina,

Thanks for your great work! I'm trying to apply role question prediction to my custom set of sentences. While trying to run this, I ran into an issue where the expected format in the __init__ of PropBankRoleFinder in `srl_as_qa_parser/role.py` does not match the format in `frames.ontonotes.jsonl`. Copy & pasting the relevant part:

```
class PropBankRoleFinder:
    def __init__(self, predicates):
        # {"predicate": "abduct", "pos": "v",
        #     "role_sets": [
        #           {"sense_id": 1, "roles": [{"type": "ARG0", "desc": "agent"},
        #                                     {"type": "ARG1", "desc": "person kidnapped"}]}]}
        self.pred_to_rolesets = {f"{prd['predicate']}-{prd['pos']}": prd['role_sets']
                                 for prd in predicates}
```

but the actual entry in the `frames.ontonotes.jsonl` file has the key 'pos' nested in each dictionary item under 'role_sets' as follows:

```
{"predicate": "abduct", "role_sets": [{"sense_id": "01", "sense_particle": "_", "pos": "v", "roles": [{"type": "A0", "desc": "agent"}, {"type": "A1", "desc": "person kidnapped"}]}]}
```

which results in the following error message just running it with the `debug_file.jsonl` in the codebase as input:

```
Traceback (most recent call last):
  File "RoleQGeneration/predict_questions.py", line 141, in <module>
    main(ap.parse_args())
  File "RoleQGeneration/predict_questions.py", line 130, in main
    get_questions(args.infile, args.outfile, args.transformation_model_path, args.device_number, args.with_adjuncts)
  File "RoleQGeneration/predict_questions.py", line 69, in get_questions
    role_finder = PropBankRoleFinder.from_framefile('role_lexicon/frames.ontonotes.jsonl')
  File "RoleQGeneration/srl_as_qa_parser/role.py", line 54, in from_framefile
    return cls(predicates)
  File "RoleQGeneration/srl_as_qa_parser/role.py", line 23, in __init__
    self.pred_to_rolesets = {f"{prd['predicate']}-{prd['pos']}": prd['role_sets']
  File "RoleQGeneration/srl_as_qa_parser/role.py", line 23, in <dictcomp>
    self.pred_to_rolesets = {f"{prd['predicate']}-{prd['pos']}": prd['role_sets']
KeyError: 'pos'
```

I tried a patchy fix myself where i just take the pos of the first dictionary item in the list role_sets to create `f"{prd['predicate']}-{prd['pos']}": prd['role_sets']`, but it looks like this patch results in the code not finding many of the predicates. What would be a proper fix?

Thanks so much!

**Comment by ValentinaPy** [comment]
Hi Najoung,

you are right, thanks for finding this bug! I added the correct frames.jsonl file now, and changed the path in the script. Thanks for pointing this out. Let me know if other issues arise.
