### ISSUE TITLE
Broken Model Link

### ISSUE THREAD

**Issue by nehasrikn** [ValentinaPy/RoleQGeneration#5]
Hi y'all! Thanks for your great work!

It looks like your [link to download model weights](https://github.com/ValentinaPy/RoleQGeneration#easy-way-to-predict-role-questions) is broken. We'd like to run your trained model on some custom data -- is there anyway to fix it?

**Comment by ValentinaPy** [comment]
Hi,
I just tested the link and it works perfectly fine (as soon as I click [on the link](https://nlp.biu.ac.il/~pyatkiv/roleqsmodels/question_transformation.tar.gz), the download to a 1.23 GB zipped file starts). The download might take a while depending on your internet speed (it takes me about 10min).
